//
// Generated file, do not edit! Created by opp_msgc 4.3 from PriorityEtherFrame.msg.
//

#ifndef _PRIORITYETHERFRAME_M_H_
#define _PRIORITYETHERFRAME_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "EtherFrame_m.h"
// }}



/**
 * Class generated from <tt>PriorityEtherFrame.msg</tt> by opp_msgc.
 * <pre>
 * packet PriorityEtherFrame extends EtherFrame {
 *     int priority;
 * };
 * </pre>
 */
class PriorityEtherFrame : public ::EtherFrame
{
  protected:
    int priority_var;

  private:
    void copy(const PriorityEtherFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PriorityEtherFrame&);

  public:
    PriorityEtherFrame(const char *name=NULL, int kind=0);
    PriorityEtherFrame(const PriorityEtherFrame& other);
    virtual ~PriorityEtherFrame();
    PriorityEtherFrame& operator=(const PriorityEtherFrame& other);
    virtual PriorityEtherFrame *dup() const {return new PriorityEtherFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPriority() const;
    virtual void setPriority(int priority);
};

inline void doPacking(cCommBuffer *b, PriorityEtherFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PriorityEtherFrame& obj) {obj.parsimUnpack(b);}


#endif // _PRIORITYETHERFRAME_M_H_
