/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_cuni_mff_d3s_deeco_simulation_Simulation */

#ifndef _Included_cz_cuni_mff_d3s_deeco_simulation_Simulation
#define _Included_cz_cuni_mff_d3s_deeco_simulation_Simulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_Simulation
 * Method:    getCurrentTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_Simulation_getCurrentTime
  (JNIEnv *, jobject);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_Simulation
 * Method:    initializeHost
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_Simulation_initializeHost
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_Simulation
 * Method:    broadcastPacket
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_Simulation_broadcastPacket
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     cz_cuni_mff_d3s_deeco_simulation_Simulation
 * Method:    run
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL _Java_cz_cuni_mff_d3s_deeco_simulation_Simulation_run
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
